name: 'Mental health influence action'
author: 'egrzeszczak'
description: 'This action checks if this repository will have a positive impact on developers mental health'
inputs:
  root_dir:
    description: 'Starting location for searching dangerous files'
    required: false,
    default: './'
runs:
  using: node16
  main: index.js
branding:
  icon: 'smile'
  color: 'green'
